### ISSUE TITLE
Update simplify() to use tables

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#138]
Both in C code and in high-level tests.

**Comment by petrelharp** [comment]
As we discussed elsewhere, I've implemented an alternative simplify algorithm that moves up through time rather than along the sequence.  There's enough that I put it on a new branch:
  https://github.com/petrelharp/msprime/tree/bottomup_simplify/temp

It currently is not quite right because it does not check if the next edgeset it is outputting is the same as the last one and so can be merged; other than this I think it is correct but haven't tested it much (as you can see).

**Comment by jeromekelleher** [comment]
Thanks @petrelharp, this is great! Unfortunately I'm travelling for the next few days and I'm not sure when I'll have a chance to take a look at it.

**Comment by jeromekelleher** [comment]
Close in #209.
