### ISSUE TITLE
check for multiple roots and throw errors

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#216]
For some things multiple roots cause problems - namely, genotyping when there is not a single ancestral state.  We need to notice this and throw an error or at least a warning.

**Comment by jeromekelleher** [comment]
Also:
- We need to add ``tree.roots`` instance variable which lists the roots. If ``tree.num_roots == 1``, then the current ``tree.root`` will return ``tree.roots[0]``. Otherwise, it will raise an Exception, since referring to single root when multiple are present could lead to very nasty bugs.

- Need to update the tree generation algorithm to keep track of all the list of roots (currently assumes that there is a single root).

**Comment by jeromekelleher** [comment]
Closed by #269
