### ISSUE TITLE
unused node (or something) causes bad trees

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#230]
Here is a MWE.  Reading this in and simplifying causes it to forget what happens to input node 11 past 0.9; for some reason, removing unused node 3 fixes this.
```
import msprime
import six

n = """\
id    is_sample    population    time
0     0    0        6.0
1     0    0        2.0
2     0    0        2.0
3     0    0        2.0
4     0    0        2.0
5     0    0        1.0
6     0    0        1.0
7     0    0        1.0
8     1    0        0.0
9     1    0        0.0
10    1    0        0.0
11    1    0        0.0
12    1    0        0.0
"""

e = """\
id    left   right  parent  children
0     0.0    0.8    5       9
1     0.3    1.0    5       10
2     0.0    1.0    6       8
3     0.0    0.3    6       10
5     0.0    0.9    7       11
6     0.0    1.0    7       12
7     0.8    1.0    7       9
4     0.9    1.0    1       11
9     0.4    1.0    1       6
11    0.0    0.4    4       6
12    0.0    1.0    4       7
8     0.0    1.0    0       1,2,4,5
"""

ts = msprime.load_text(six.StringIO(n), six.StringIO(e))

sts = ts.simplify()
stst = sts.trees()
for t in stst:
    print(t.parent(3))
```

The true trees should be
```
0.0 to 0.3:
    {12:7, 11:7, 10:6, 9:5, 8:6, 7:4, 6:4, 5:0, 4:0, 2:0, 1:0}
0.3 to 0.4:
    {12:7, 11:7, 10:5, 9:5, 8:6, 7:4, 6:4, 5:0, 4:0, 2:0, 1:0}
0.4 to 0.8:
    {12:7, 11:7, 10:5, 9:5, 8:6, 7:4, 6:1, 5:0, 4:0, 2:0, 1:0}
0.8 to 0.9:
    {12:7, 11:7, 10:5, 9:7, 8:6, 7:4, 6:1, 5:0, 4:0, 2:0, 1:0}
0.9 to 1.0:
    {12:7, 11:1, 10:5, 9:7, 8:6, 7:4, 6:1, 5:0, 4:0, 2:0, 1:0}
```

**Comment by jeromekelleher** [comment]
Superb, thanks @petrelharp. I'll sort this out ASAP.

**Comment by jeromekelleher** [comment]
These records don't make sense topologically @petrelharp --- e.g., the first two records contradict each other. I got caught out with exactly this problem a couple of days ago as well, so I decided it was time to add proper checks for these topological properties. This should be done over at #232.

One question remains though: what should simplify do when given these topologically malformed tree sequences? Once we can guarantee safety (i.e., no memory violations or infinite loops) I'm happy with a "garbage-in-garbage-out" approach here. Otherwise, we'll have to import into a tree sequence and run through the trees to find out if these problems exist.

**Comment by petrelharp** [comment]
I'm not seeing it -- what is contradictory?  This passes the check I implemented [here](https://github.com/jeromekelleher/msprime/pull/231/files#diff-e7d43041d4b0d31332fd3ca49a132fbdR60), i believe, for instance.

**Comment by petrelharp** [comment]
Ah - overlapping edgesets?  But, these are allowed by `simplify` - is it only `simplify_tables`?

**Comment by petrelharp** [comment]
Re: GIGO - I'm good with that - besides the checks already in, I think we'd basically have to either construct all the trees (like you just put in) or run the whole simplify algorithm (with added checks).

**Comment by jeromekelleher** [comment]
These two edgesets are contradictory as far as the tree generation algorithm is concerned:
```
id    left   right  parent  children
0     0.0    0.8    5       9
1     0.3    1.0    5       10
```
Over (0.3, 0.8], the first says the child of 5 is 9, and over the same interval the second says that the child of 5 is 10. Not that it's not mathematically possible to infer that there is in fact two children over this interval, but this is not how the tree generation algorithm sees it. I think it would add a lot of complexity if we allowed for "additive" children lists like this. (Could be convinced otherwise of course, this is just my current view point.)

Does this make sense, and is it in line with your assumptions?

**Comment by petrelharp** [comment]
OK, we're on the same page - overlapping edgesets - the problem was that I thought `simplify` took care of this.

So, here's the real problem:
```
>>> for x in sts.dump_tables():
...     print(x)
... 
id	flags	population	time
0	1	0		0.00000000000000
1	1	0		0.00000000000000
2	1	0		0.00000000000000
3	1	0		0.00000000000000
4	1	0		0.00000000000000
5	0	0		1.00000000000000
6	0	0		1.00000000000000
7	0	0		1.00000000000000
8	0	0		2.00000000000000
9	0	0		6.00000000000000
id	left		right		parent	children
0	0.30000000	0.80000000	5	1,2
1	0.00000000	0.30000000	6	0,2
2	0.00000000	0.80000000	7	3,4
3	0.80000000	0.90000000	7	1,3,4
4	0.90000000	1.00000000	7	1,4
5	0.00000000	0.30000000	8	6,7
6	0.30000000	0.40000000	8	0,7
7	0.00000000	0.30000000	9	1,8
8	0.30000000	0.40000000	9	5,8
9	0.40000000	0.80000000	9	0,5,7
10	0.80000000	1.00000000	9	0,2,7
```
... note there is no record that says what happens to `3` on `[0.9,1.0)`.

**Comment by petrelharp** [comment]
The python version in `tests` works correctly on this, btw.

**Comment by jeromekelleher** [comment]
Ah, rightyho, I'm just being slow. I hadn't considered overlapping edgesets for simplify, but you're right it is a big advantage if ``simplify`` takes care of this. I'll have a quick dig into this later and see if I can sort it out. Can't be a serious issue if the Python version works correctly.
