### ISSUE TITLE
Different edge sets are considered sorted, resulting in different mutations output.

### ISSUE THREAD

**Issue by molpopgen** [jeromekelleher/msprime#249]
Regarding the master branch, the docs describe the sorting of edge sets.  I have found that two different edge sets representing the same ancestry can both be considered sorted.  When used to populate trees and throw down mutations, the outputs are different.  I discovered this by implementing a sorting algorithm in C++ that resulted in "loadable" edge sets (e.g., no error raised), but then the mutations differed from what I got from using `msprime.sort_tables()`.

An example script is found [here](https://github.com/molpopgen/fwdpy11_arg_example/blob/msprime_integration_streamline_indexing/practice/sorting.py).  It uses the same node table and two subtly different EdgesetTables (they differ in the order of two rows, and msprime considers both to be correctly sorted):

Nodes:
```
id	flags	population	time
0	1	0		0.00000000000000
1	1	0		0.00000000000000
2	1	0		0.00000000000000
3	0	0		0.40000000000000
4	0	0		0.50000000000000
5	0	0		0.70000000000000
6	0	0		1.00000000000000
```

EdgesetTable 1:
```
id	left		right		parent	children
0	0.20000000	0.80000000	3	0,2
1	0.00000000	0.20000000	4	1,2
2	0.20000000	0.80000000	4	1,3
3	0.80000000	1.00000000	4	1,2
4	0.80000000	1.00000000	5	0,4
5	0.00000000	0.20000000	6	0,4
```

EdgesetTable 2:
```
id	left		right		parent	children
0	0.20000000	0.80000000	3	0,2
1	0.00000000	0.20000000	4	1,2
2	0.80000000	1.00000000	4	1,2
3	0.20000000	0.80000000	4	1,3
4	0.80000000	1.00000000	5	0,4
5	0.00000000	0.20000000	6	0,4
```

When I throw mutations onto each with the same seed, I get different mutations out.

For table 1:

```
id	position	ancestral_state
0	0.01128232	0
1	0.12022300	0
2	0.14439975	0
3	0.23485017	0
4	0.29361118	0
5	0.30909498	0
6	0.31004271	0
7	0.55919509	0
8	0.63919636	0
9	0.80141326	0
10	0.92237058	0
```

And for table 2:

```
id	position	ancestral_state
0	0.00929008	0
1	0.01128232	0
2	0.10284689	0
3	0.12022300	0
4	0.14439975	0
5	0.23485017	0
6	0.28369632	0
7	0.29361118	0
8	0.37473748	0
9	0.45916701	0
10	0.55919509	0
11	0.63919636	0
12	0.80015575	0
13	0.81812129	0
14	0.84655427	0
15	0.92349630	0
```

**Comment by molpopgen** [comment]
I think some confusion may arise from this line in the docs:

```
The list of offspring in an edgeset must be sorted.
```

It is not clear how they should be sorted:

* Lexically sort the tuples of children?
* Numerically sort on left or (left,right)?
* Some combo?

**Comment by jeromekelleher** [comment]
Well spotted, thanks @molpopgen. In this case I think it's harmless (i.e., the mutations generated are both drawn from the correct distribution), but there is definitely some ambiguity in the documentation here. 

For msprime.sort_tables, edgesets are sorted as follows:

1. By the time of the parent node;
2. If time values of different nodes are equal, sort by the node value;
3. If node values are equal, sort by the left coordinate.

(1) and (2) are essential for correctness of simplify, and are verified by msprime during input. I put in (3) just to get rid of any ambiguity when different sort algorithms are used, so that the output of msprime.simplify_tables is always equal across different platforms. 

(I have hit this problem before: glibc's qsort is a stable sort, while OSX's version is not. So, there will be differences between the outputs of the program on different platforms, unless all sort dimensions are fully specified. Not that it matters much, but it's an annoying noise when trying to track down real problems otherwise.)

So, the question is, do we make (3) an input requirement? It's a handy property to have sometimes, but it might be overspecification to require it. What do you think @petrelharp?

Re. sorting children, this just refers to the numerical ordering of the children within a *single* edgeset. This requirement is there to (a) break an annoying symmetry;  and (b) make finding children within a large edgeset (suppose a particular node has 10000 children) more efficient. We could probably relax this requirement for ``simplify_tables`` though, since the sortedness property isn't used.

**Comment by petrelharp** [comment]
Huh, turns out I was confused about this.  I thought of (3) as a
requirement, but I think I was just confused with how records are used in
generating the tree sequence.

I think it's a fine thing to require - we already make these other
requirements, and provide a sort function; and it could be useful to assume.

On the other hand, it would then require checking for sorteness, and would
make it somewhat harder for people to get on board with their own
examples.  So, I could go either way, but I lean towards requiring it.

--p

**Comment by molpopgen** [comment]
For the sake of sanity, reproducibility, and apparently portability (GCC vs clang as @jeromekelleher points out--I assume it isn't as simple as Linux vs OS X, and that OS X + conda's gcc would provide a stable sort?), it may be safest to require that all fields be sorted.  For example, if we consider the edge sets as a list of tuples `(parent time, parent id, child id, left, right)`, then a function can be defined that results in a single sorted list:

```py
def sort_edges(lhs, rhs):
    if lhs.time != rhs.time:
        return ls.time > rhs.time
    if lhs.parent != rhs.parent:
       return lhs.parent < rhs.parent
    if lhs.child != rhs.child:
       return lhs.child < rhs.child
    #likewise for left and right...
```




Otherwise, the requirement is that edge sets are partially sorted, and a `.. warning::` may be warranted in the docs that the output of dropping mutations is affected by the sorting:

Although the example above is harmless when considering the distribution of outcomes, it was concerning to me that I was getting different outputs.  In fact, I have been unable to arrive at a sorted edge set list that gives the same output as `msprime.sort_tables()`!

**Comment by molpopgen** [comment]
> In fact, I have been unable to arrive at a sorted edge set list that gives the same output as msprime.sort_tables()!

I finally did figure it out, but my implementation is terribly slow at the moment :).

**Comment by jeromekelleher** [comment]
Thanks for the input @petrelharp and @molpopgen. I agree, let's make it a requirement that edgesets are also sorted by left coordinate. I don't think it'll be hard to detect on input, and it is a useful property to have.

Re sorts, @molpopgen, I don't know the exact details, but glibc's qsort is stable and the sort from whatever libc OSX borrows from FreeBSD  isn't. I don't think it's a compiler thing, but I wouldn't be surprised if installing gcc on OSX involved pulling in glibc and linked against it by default as well. Just another portability gotcha to be aware of and worked around...

**Comment by jeromekelleher** [comment]
Added #252 to capture the new requirement. Can you close this issue if you are happy it's been resolved please @molpopgen?

**Comment by molpopgen** [comment]
> Re sorts, @molpopgen, I don't know the exact details, but glibc's qsort is stable and the sort from whatever libc OSX borrows from FreeBSD isn't. I don't think it's a compiler thing, but I wouldn't be surprised if installing gcc on OSX involved pulling in glibc and linked against it by default as well. Just another portability gotcha to be aware of and worked around...

I'm just curious--do you have a test of this.  C does not require qsort to be stable, and the GNU folks [say it is not stable](https://www.gnu.org/software/libc/manual/html_node/Array-Sort-Function.html).  C++ distinguishes `std::sort` (which is qsort) from `std::stable_sort`, which generates the necessary lookup stuff for stability.

**Comment by molpopgen** [comment]
Closing.  Things moving over to #252.

**Comment by jeromekelleher** [comment]
> I'm just curious--do you have a test of this? C does not require qsort to be stable, and the GNU folks say it is not stable. C++ distinguishes std::sort (which is qsort) from std::stable_sort, which generates the necessary lookup stuff for stability.

I guess they say it's unstable in the manual just to make sure that people don't depend on the sort stability. Internally though glibc often uses mergesort as the actual sorting algo, which is stable. Since the standard doesn't require it to be stable they can do what they like I guess. It might vary with glibc version too.

**Comment by petrelharp** [comment]
A small note: in practice I think that things will be close to sorted,
which might affect the choice of sort algorithm?

**Comment by molpopgen** [comment]
> A small note: in practice I think that things will be close to sorted,
> which might affect the choice of sort algorithm?

In principle, yes.  In practice, you have either what your standard library gives you (usually quick sort), or whatever you are willing to write yourself or introduce a dependency for.  More generally, things could be very far from sorted if one imagines doing this stuff in parallel.  You'd probably end up with small sets of sorted things, with those sets themselves being fairly random in order.

**Comment by petrelharp** [comment]
Oh, good.  So we can ignore this. =)

On Mon, Aug 28, 2017 at 3:24 PM, Kevin R. Thornton <notifications@github.com

**Comment by molpopgen** [comment]
> Oh, good.  So we can ignore this. =)

Yep, and it wouldn't even be something I'd consider unless profiling told me I was spending most of my time sorting things.

**Comment by jeromekelleher** [comment]
> Yep, and it wouldn't even be something I'd consider unless profiling told me I was spending most of my time sorting things.

+100!

Re. the almost sorted point, I would imagine that we can include offset arguments to ``sort_tables`` that tell the library that everything up to a given offset is already sorted. This will probably map well to the ``append_columns`` usage and cut down the sorting time pretty dramatically.
