### ISSUE TITLE
allow tracking samples of more than one sample set

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#297]
Currently the `num_tracked_samples` machinery only allows for tracking *one* set of samples.  For general statistics as in #290, and also (as I will argue elsewhere) for doing LD with more than two alleles, we need to follow more than one.  This is basically what is happening [here](https://github.com/jeromekelleher/msprime/pull/290/files#diff-71c56ecf7eccce3069862f1392a93974R805). To do this, we could:

1. change the `TreeSequence.trees()` interface to allow a *list* of tracked samples, so that we could e.g. do
    ```
    for t in ts.trees(tracked_samples=[[0,1,2], [1,3,5]], sample_counts=True):
      print t.get_num_tracked_samples(1)
    ```
    ... returning for each tree a list of length 2.

2. just use the existing `sample_lists` method, which I imagine would be inefficient

3. add another set of arguments to `.trees()`, e.g. `tracked_sample_list=[[0,1,2], [1,3,5]]`, retaining the previous UI as a special case of this.

4. implement this functionality in C but not at the python level.

... or something else?  The third thing would break the least existing code, but adds an unfortunate number of similar-sounding options.

Also for your consideration: currently this works by assigning each tracked sample weight one, then computing for each internal node the total weight below that node.  I anticipate it being useful in the future to have different sets of weights.  For instance, suppose I want to compute a statistic that is: pick a sample from a Gaussian distribution centered at `x` with `sd=1 km` and pick another sample from a Gaussian centered at `y`, also with `sd=1 km`; and find the sequence divergence between the two.  Currently to do this we'd have to compute the whole matrix of pairwise divergences; but with weights it'd be easy.  Is this the time to add in weights, that default to 1?

**Comment by jeromekelleher** [comment]
Thanks @petrelharp, these are good ideas. I agree we'll want to have some general way of tracking sets of samples. The first question to get out of the way though it this: why not just run two parallel tree iterations, each tracking different sets of tracked leaves? i.e.

```python
trees1 = ts.trees(tracked_samples=[0, 1, 2])
trees2 = ts.trees(tracked_samples=[1, 3, 5])
for t1, t2 in zip(trees1, trees2):
    ns1 = t1.num_tracked_samples(1)
    ns2 = t2.num_tracked_samples(1)
```
Obviously this approach has a higher memory overhead and larger constants than allowing for lists of tracked samples, but asymptotically it's the same. 

> Also for your consideration: currently this works by assigning each tracked sample weight one, then computing for each internal node the total weight below that node. I anticipate it being useful in the future to have different sets of weights. For instance, suppose I want to compute a statistic that is: pick a sample from a Gaussian distribution centered at x with sd=1 km and pick another sample from a Gaussian centered at y, also with sd=1 km; and find the sequence divergence between the two. Currently to do this we'd have to compute the whole matrix of pairwise divergences; but with weights it'd be easy. Is this the time to add in weights, that default to 1?

Interesting. Yes, weights sounds like a good addition.

My overriding sense here is that it's been far too long since we've made a release (0.4.0 is nearly a year old now), and we should try to wrap up what we have now and make it available before adding any more features. If we can do what we need to do now without weights and changing the ``tracked_samples`` API, I would prefer to take that approach.

**Comment by petrelharp** [comment]
Oh, that's even better!  Ok, sounds good.

We will save "weights" for the future.
