### ISSUE TITLE
Regarding msprime 0.4.1

### ISSUE THREAD

**Issue by LauritsSkov** [jeromekelleher/msprime#312]
I cannot find version 0.4.1 on Bioconda or Pypi - would it be possible for you to update the packages?

I want to be able to set the "record_migrations = True" parameter when I simulate my sequences.

**Comment by jeromekelleher** [comment]
Sorry @LauritsSkov, we haven't released this functionality yet. We're working hard on getting a release out as soon as possible, but it'll be another month or two most likely. Big changes have been made under the hood, and we want to be sure that all the new APIs are settled and properly documented before releasing.

If you want to use migration recording, you'll need to install from github. This is straightforward: just check out the master branch, and run ``pip install . `` from within the directory. Apologies once again for this, it has been far too long since the last release!

**Comment by jeromekelleher** [comment]
Sorry, I meant to get back to you here @LauritsSkov when 0.5.0 was released. The migrations functionality has been released and documented now, and is available on pypi and conda.

**Comment by LauritsSkov** [comment]
Hey Jerome.


Great work I am very much looking forward to using your software!

________________________________
Fra: Jerome Kelleher <notifications@github.com>
Sendt: 3. marts 2018 20:26
Til: jeromekelleher/msprime
Cc: Laurits Skov; Mention
Emne: Re: [jeromekelleher/msprime] Regarding msprime 0.4.1 (#312)


Sorry, I meant to get back to you here @LauritsSkov<https://github.com/lauritsskov> when 0.5.0 was released. The migrations functionality has been released and documented now, and is available on pypi and conda.

-
