### ISSUE TITLE
remove `node_map` option?

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#316]
It is worrisome to keep that `node_map` optional argument for `simplify` and `simplify_tables`.  I think if we were to change the behavior of simplify in the future to re-order the samples, then that would break much existing code that uses it and assumes its current behavior.  So, how about either

1. remove the option
2. require the option, making it non-optional

... and I vote for (1).

**Comment by jeromekelleher** [comment]
It's useful though, as it returns the mapping of _all_ nodes in the existing tree sequence to their counterparts in the new tree sequence (not just the samples).  Suppose you had an internal node you were interested in (that you didn't want to make a sample), and you wanted to know what's it's new ID is. There's no way to do this without the ``map_nodes`` option.

I agree that changing the ordering in the future would be a terrible thing to do, and we should most certainly not do it. But this doesn't have any bearing on keeping the ``map_nodes`` option to ts.simplify, IMO.

So I would prefer to keep it (not least because it'd break a lot of test code now to remove it!). Am I missing something else though?

**Comment by petrelharp** [comment]
oh, right!  sorry, forgot that point.  gotcha.
