### ISSUE TITLE
Text table formats for awkward data

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#332]
One of the last remaining details to clear up before 0.5.0 is to decide how to handle the text data format for recent extensions. There are a few thorny issues:

1) How do we encode the metadata column? In principle this contains binary data, so we cannot just print it out as an utf-8 stream. On the other hand, if the column does contain text, it's a lot less useful to see a base64 encoded string than your actual JSON metadata. I think the best option here is to provide a boolean flag to force binary encoding of the metadata, but assume that the metadata is text by default. 

2) How do we deal with empty strings for ancestral and derived state (and indeed, metadata)? These are perfectly valid values now, and will cause problems with a white-space delimited file. The only real solution I can see here is to add a option to insist on tab-delimiting (allowing us to detect zero length strings), but to allow more lenient white-space delimiting by default, hopefully failing reasonably gracefully when a file with zero-length strings is provided.

Any thoughts on this @petrelharp, @ashander, @molpopgen?

**Comment by petrelharp** [comment]
Text by default = good.

Empty strings: the problem is in text-based representations of site and mutation tables?  The only other option would be to quote everything, which would be annoying; I support strict tab-delimited files.

**Comment by molpopgen** [comment]
Are we talking about representation in files, or when printed to the screen?  For the metadata, any text-based representation in files has to be a non-starter, as it would cause reasonable unit tests to fail due to the presence of floating-point values in the original data.

I'm imagining that meta-data will always be binary.  I really cannot see using JSON for this, as it has big overhead for lots of instances of small objects.   JSON would also have the same problems in causing test failures due to precision loss.  You would not be able to iterate over your simulated population and assert that you can find every mutation position or selection coefficient in your list of JSON objects.  Such a task is guaranteed to fail at some point.

I think some functional programming ideas would be handy here.  For example, asking the user to supply a callback that converts the binary metadata into something human-readable:

```python
def metatdata2txt( data ):
      x = pickle.loads(data)
      return x.__repr__() # or str(x), or some "{} {}".format() thing....
```

**Comment by jeromekelleher** [comment]
Thanks for this @molpopgen, these are convincing arguments. Lets base64 encode metadata by default then for text formatting. We can add options for custom decoding for display later, but by default we should ensure the integrity of the data.

**Comment by molpopgen** [comment]
> Thanks for this @molpopgen, these are convincing arguments. Lets base64 encode metadata by default then for text formatting. We can add options for custom decoding for display later, but by default we should ensure the integrity of the data.

One thing I realized that may be worth a mention in the manual:  it seems like an ideal format for metadata encoded from a Python source is a pickled instance of `collections.namedtuple`.  It satisfies what one wants from JSON (field names) but has the space efficiency of the regular `tuple`, is easily converted to `pandas.DataFrame` records, etc.
