### ISSUE TITLE
Reusing metadata (at least in some cases)?

### ISSUE THREAD

**Issue by molpopgen** [jeromekelleher/msprime#380]
Currently, the Tables API metadata indexes/offsets must be non-decreasing values.  However, there are cases where it would be nice to re-use metadata for multiple table rows, requiring that you be able to use the index to refer to a previous entry.

For example, when thinking about node metadata in the context of a forward simulation, the nodes will represent each element `0 < i <= P` in an individual with ploidy `P`.  In many cases, the meta data will be something about the individual and perhaps not about the node itself.  For example, the individual's fitness.  For cases like this, it would be nice to only record the metadata for the first node, and then refer back to that metadata entry for the remaining nodes.

**Comment by jeromekelleher** [comment]
This is a really neat idea, and could save a lot of space if we use the same idea for ancestral states, etc. However, I'm not sure that it can work in general, given the way offsets are defined. If we have a column with values ["0", "0", "0"], and we encode as:
```
col = ['000']
offset = [0, 1, 2, 3]
```
Then the value for row j is ``col[offset[j]:offset[j + 1]]``. Now, I don't think there's any way we can write this to reuse the repeated values such that this property holds. I.e. if we just write:
```
col = ['0'],
offsets = [0, 1, ???]
```
I don't think there's any way of writing the offsets such that this holds (unless we do something seriously funky with reversed indexing). It seems like more trouble that it's worth, to be honest.

I think the real issue here is that we're not dealing with ploidy properly. I think we basically need a new table that represents a polyploid Individual as a collection of 1 or more nodes. This is definitely something that needs to be tackled at some point. Then, we associate the metadata that you're talking about with the Individual rather than the Nodes.

**Comment by molpopgen** [comment]
That makes sense.  Another scheme we pondered was to pickle the index of the metadata of the first node as the second node's metadata.  But there's a big downside due to reindexing after simplification.

Thanks!

**Comment by jeromekelleher** [comment]
Cool. Moving this discussion to #386.
